fix(slideshow): Use EventBus to notify activities of file deletion
Reduces the coupling, using an already existing EventBus pattern.
During registration, we need to first check if it is already registered.
Otherwise, the app crashed directly at first start with the error

org.greenrobot.eventbus.EventBusException: Subscriber class
com.owncloud.android.ui.activity.FileDisplayActivity already registered to
event class com.owncloud.android.ui.events.FilesRefreshEvent

Signed-off-by: Philipp Hasper <vcs@hasper.info>